import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os

def get_project_root():
    return os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))

def main():
    root = get_project_root()

    # 1. Setup and Data Loading
    plots_dir = os.path.join(root, 'plots')
    os.makedirs(plots_dir, exist_ok=True)

    incidents = pd.read_csv(os.path.join(root, 'datasets/incidents_master.csv'))
    financial = pd.read_csv(os.path.join(root, 'datasets/financial_impact.csv'))
    market = pd.read_csv(os.path.join(root, 'datasets/market_impact.csv'))

    # Inner merge to ensure we only analyze incidents that have data in all three domains
    df = incidents.merge(financial, on='incident_id', how='inner').merge(market, on='incident_id', how='inner')

    insights = ["# 📊 Deep Relational Analysis: Operational vs. Financial vs. Market\n\n"]
    insights.append("## Analysis Process\nThis report was generated by merging incident metadata, financial losses, and market reactions. We looked for correlations between *Operational Severity* (what happened) and *Value Impact* (what it cost).\n\n")

    # 2. Defining Analysis Pairs
    # (Operational Metric, Value Metric, Title)
    pairs = [
        ('downtime_hours', 'total_loss_usd', 'Downtime vs. Total Financial Loss'),
        ('data_compromised_records', 'total_loss_usd', 'Records Lost vs. Total Financial Loss'),
        ('total_loss_usd', 'abnormal_return_1d', 'Financial Loss vs. 1-Day Stock Drop'),
        ('downtime_hours', 'days_to_price_recovery', 'Downtime vs. Market Recovery Time'),
    ]

    insights.append("## 1. Continuous Correlation Analysis\n")
    for op, val, title in pairs:
        if op in df.columns and val in df.columns:
            # Create Scatter Plot
            plt.figure(figsize=(10, 6))
            sns.scatterplot(data=df, x=op, y=val)
            plt.title(title)
            plt.grid(True, linestyle='--', alpha=0.6)

            plot_path = os.path.join(plots_dir, f"{op}_vs_{val}.png")
            plt.savefig(plot_path)
            plt.close()

            # Calculate Correlation
            corr = df[op].corr(df[val])
            insights.append(f"### {title}\n")
            insights.append(f"- **Correlation Coefficient:** {corr:.3f}\n")
            insights.append(f"- **Visual Evidence:** `plots/{op}_vs_{val}.png`\n")

            # Interpretation logic
            if abs(corr) > 0.7: strength = "Strong"
            elif abs(corr) > 0.4: strength = "Moderate"
            else: strength = "Weak"
            insights.append(f"- **Verdict:** {strength} relationship. " +
                            ("Directly proportional" if corr > 0 else "Inversely proportional") + ".\n\n")

    # 3. Categorical Impact (Boxplots)
    insights.append("## 2. Categorical Impact Analysis\n")
    categorical_cols = ['attack_vector_primary', 'industry_primary']
    value_metrics = ['total_loss_usd', 'abnormal_return_1d']

    for cat in categorical_cols:
        for val in value_metrics:
            if cat in df.columns and val in df.columns:
                plt.figure(figsize=(12, 6))
                sns.boxplot(data=df, x=cat, y=val)
                plt.xticks(rotation=45, ha='right')
                plt.title(f"{cat} Impact on {val}")

                plot_path = os.path.join(plots_dir, f"{cat}_impact_{val}.png")
                plt.savefig(plot_path)
                plt.close()

                insights.append(f"### {cat} vs {val}\n")
                insights.append(f"- **Visual Evidence:** `plots/{cat}_impact_{val}.png`\n")

                # Find the most impactful category
                top_cat = df.groupby(cat)[val].mean().idxmax()
                top_val = df.groupby(cat)[val].mean().max()
                insights.append(f"- **Key Finding:** {top_cat} has the highest average impact ({top_val:.2f}).\n\n")

    # Write report
    output_path = os.path.join(root, 'documentations/comparative_insights.md')
    with open(output_path, 'w') as f:
        f.write("\n".join(insights))

    print(f"Deep relational analysis complete. Check 'plots/' folder and 'documentations/comparative_insights.md'.")

if __name__ == "__main__":
    main()
